### ISSUE TITLE
you could replace that by `thisPlugin._tracer.bind(this._otContext, originalThen)` (interally it does almost the same but it would be clearer for you i think)

### ISSUE THREAD

**Issue by wdalmut** [wdalmut/opentelemetry-plugin-mongoose#35]
you could replace that by `thisPlugin._tracer.bind(this._otContext, originalThen)` (interally it does almost the same but it would be clearer for you i think)

_Originally posted by @vmarchaud in https://github.com/wdalmut/opentelemetry-plugin-mongoose/pull/34/files/4974498d305857fcbe8829f9c0253d45e4387dee_

**Comment by BlumAmir** [comment]
Thank @wdalmut  you for writing and maintaining this plugin.
Regarding the issue, I think we can even improve it more by [starting the new span](https://github.com/wdalmut/opentelemetry-plugin-mongoose/blob/master/src/mongoose.ts#L55) in patched `exec()` with the relevant captured context stored on the query. The [startSpan function](https://github.com/open-telemetry/opentelemetry-js/blob/master/packages/opentelemetry-tracing/src/Tracer.ts#L66) receives a `context` argument  which defaults to `api.context.active()`, but we can send the relevant context there, and remove the patching for `then` in the plugin.
If you like it I can create a PR.

**Comment by blumamir** [comment]
Sent a PR #40 that solves this issue, and make the patching of `then` function redundant.
