### ISSUE TITLE
[Question] Trace aggregate

### ISSUE THREAD

**Issue by PierreAndreis** [wdalmut/opentelemetry-plugin-mongoose#38]
Does this plugin support tracing of `aggregate` queries? 

I have noticed that it is not included on the filter in https://github.com/wdalmut/opentelemetry-plugin-mongoose/blob/master/src/mongoose.ts#L11-L26

**Comment by wdalmut** [comment]
I can a testcase for this. Can you attach your aggregate query so i can a more real testcase?
thanks

**Comment by PierreAndreis** [comment]
@wdalmut Thank you so much. I would love to contribute to this plugin as well. I'm not familiar at all with open telemetry and it would take me a while to get going, but let me know in case you don't have time to do it and I will try my best.

An example of mongoose aggregate is:
```typescript
Model.aggregate([
                     { $match: { status: "A" } },
                     { $group: { _id: "$cust_id", total: { $sum: "$amount" } } },
                     { $sort: { total: -1 } }
                   ]);
```

**Comment by BlumAmir** [comment]
I tested it and looks like `model.aggregate` calls are not instrumented.
Aggregate object has [it's own exec() function](https://github.com/Automattic/mongoose/blob/master/lib/aggregate.js#L945) which is currently not patched.
I think we need patch the `Aggregate.prototype.exec` function in a similar way to `Query.prototype.exec()`:
```js 
shimmer.wrap(this._moduleExports.Aggregate.prototype, 'exec', this.patchAggregateExec());
```
And take care of capturing opentelemetry context to avoid unlinked spans like in #29

**Comment by blumamir** [comment]
submitted a PR that should solve this issue.
https://github.com/wdalmut/opentelemetry-plugin-mongoose/pull/39
